Repository go-gitea/lgtm, pull requests merged in 2020-12, with the labels that each got.

#44 Update drone
  .drone.yml
  Makefile
  go.mod
  go.sum
  vendor/github.com/franela/goblin/.travis.yml
  vendor/github.com/franela/goblin/README.md
  vendor/github.com/franela/goblin/assertions.go
  vendor/github.com/franela/goblin/go.mod
  vendor/github.com/franela/goblin/go.snippets
  vendor/github.com/franela/goblin/goblin.go
  vendor/github.com/franela/goblin/goblin_output.png
  vendor/github.com/franela/goblin/mono_reporter.go
  vendor/github.com/franela/goblin/reporting.go
  vendor/modules.txt
Labels: kind/testing, lgtm/need 1

#47 Run DB tests on pulls too
  .drone.yml
Labels: kind/testing, lgtm/done

#45 Update MAINTAINERS file based on go-gitea/gitea
  MAINTAINERS
Labels: kind/docs, lgtm/done

#48 drone: rm updater
  .drone.yml
Labels: kind/deployment
